//-- Variables. https://www.youtube.com/embed/ ?autoplay=1&loop=1&playlist= &controls=0&rel=0
var videosIDserbia =
[
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/embed/WwLNX99kb6A?autoplay=1&loop=1&playlist=WwLNX99kb6A&controls=0&rel=0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/embed/Z25Z1l-sFmI?autoplay=1&loop=1&playlist=Z25Z1l-sFmI&controls=0&rel=0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/embed/W1Obgu2YlcQ?autoplay=1&loop=1&playlist=W1Obgu2YlcQ&controls=0&rel=0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/embed/NNAAGDnMwMY?autoplay=1&loop=1&playlist=NNAAGDnMwMY&controls=0&rel=0",
    "",
    "",
    "",
    "https://www.youtube.com/embed/E7d913JBHFg?autoplay=1&loop=1&playlist=E7d913JBHFg&controls=0&rel=0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/embed/VCq5uBjleLQ?autoplay=1&loop=1&playlist=VCq5uBjleLQ&controls=0&rel=0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "https://www.youtube.com/embed/rd4ynoeNLjc?autoplay=1&loop=1&playlist=rd4ynoeNLjc&controls=0&rel=0",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];
var imagenesIDserbia =
[
    "https://i.postimg.cc/6p1p8vD9/1.jpg",
    "https://i.postimg.cc/CKBLkKgb/2.jpg",
    "https://i.postimg.cc/9QffXpg8/3.jpg",
    "https://i.postimg.cc/j5YKfQvr/6.jpg",
    "https://i.postimg.cc/nLJRvt0R/7.jpg",
    "https://i.postimg.cc/hv6MhFX0/4.jpg",
    "https://i.postimg.cc/bNS3Wv5V/5.jpg",
    "https://i.postimg.cc/mgbVDSDJ/8.jpg",
    "",
    "https://i.postimg.cc/L6VBrZTT/9.jpg",
    "https://i.postimg.cc/mr2J3PjZ/10.jpg",
    "https://i.postimg.cc/857Y3xxq/11.jpg",
    "https://i.postimg.cc/FKWqThCy/12.jpg",
    "https://i.postimg.cc/VkzV1J39/DSC-0315.jpg",
    "https://i.postimg.cc/Fs56WWpB/DSC-0344.jpg",
    "https://i.postimg.cc/VvMVsnfg/DSC-0345.jpg",
    "https://i.postimg.cc/SN6vw6tN/DSC-0348.jpg",
    "https://i.postimg.cc/G3sNjwFD/DSC-0350.jpg",
    "https://i.postimg.cc/rySqVYhS/13.jpg",
    "https://i.postimg.cc/NfBB57VZ/14.jpg",
    "https://i.postimg.cc/52rhqw74/IMG-9124.jpg",
    "https://i.postimg.cc/Fznp5xJ1/15.jpg",
    "https://i.postimg.cc/hjsMMnDL/16.jpg",
    "https://i.postimg.cc/7PBm2qQD/17.jpg",
    "https://i.postimg.cc/sx2mNLxt/18.jpg",
    "https://i.postimg.cc/DzKgT0mQ/19.jpg",
    "https://i.postimg.cc/Yqh8NTJF/20.jpg",
    "https://i.postimg.cc/L6wDxNpb/21.jpg",
    "https://i.postimg.cc/GmDQVG3h/22.jpg",
    "https://i.postimg.cc/xdyPTQbw/23.jpg",
    "https://i.postimg.cc/C1hsR2Gz/24.jpg",
    "https://i.postimg.cc/50sqLmgp/25.jpg",
    "https://i.postimg.cc/5yj53FkJ/26.jpg",
    "https://i.postimg.cc/vTjrSHpV/27.jpg",
    "https://i.postimg.cc/59kStn62/28.jpg",
    "https://i.postimg.cc/9F7ZQ26L/29.jpg",
    "https://i.postimg.cc/9QP9ypFT/30.jpg",
    "",
    "https://i.postimg.cc/YCBg4VkM/31.jpg",
    "https://i.postimg.cc/HxZQQ5F4/32.jpg",
    "https://i.postimg.cc/ZqSpmzW1/33.png",
    "https://i.postimg.cc/6q8CzqXs/34.jpg",
    "https://i.postimg.cc/RFV76GpZ/35.jpg",
    "https://i.postimg.cc/Ghsky4KG/36.jpg",
    "https://i.postimg.cc/jq1H2HHR/37.jpg",
    "https://i.postimg.cc/g2F3qGt5/38.jpg",
    "https://i.postimg.cc/nzzmcrMs/39.jpg",
    "https://i.postimg.cc/wMRsLrXg/40.jpg",
    "https://i.postimg.cc/NLh24xDT/41.jpg",
    "https://i.postimg.cc/QtyTBDWf/42.jpg",
    "https://i.postimg.cc/FHc3wHHy/43.png",
    "https://i.postimg.cc/2j1H08T8/44.jpg",
    "https://i.postimg.cc/zGFXLyDX/IMG-9241.jpg",
    "https://i.postimg.cc/DwTwyrTM/IMG-9461.jpg",
    "https://i.postimg.cc/Qx5M36R7/IMG-9476.jpg",
    "https://i.postimg.cc/Y2TSTcyk/IMG-9542.jpg",
    "https://i.postimg.cc/ryDmhyjQ/IMG-9543.jpg",
    "https://i.postimg.cc/5yhDgSgd/IMG-9676.jpg",
    "https://i.postimg.cc/qqh9258x/IMG-9742.jpg",
    "https://i.postimg.cc/LsvKSf9L/IMG-9743.jpg",
    "https://i.postimg.cc/tTmKZjVg/IMG-9892.jpg",
    "https://i.postimg.cc/G220m2tN/IMG-9903.jpg",
    "https://i.postimg.cc/3wwBVDdk/45.jpg",
    "",
    "https://i.postimg.cc/MKW6jyHM/46.jpg",
    "https://i.postimg.cc/m28b3t1d/47.jpg",
    "https://i.postimg.cc/xjGjCsfV/48.jpg",
    "https://i.postimg.cc/W1zs5TMs/49.jpg",
    "https://i.postimg.cc/tRBf2PDV/IMG-20220224-201126.png",
    "https://i.postimg.cc/jdsfdnrv/DSCF1421.jpg",
    "https://i.postimg.cc/Vs9M8B2d/PSX-20220225-211041.jpg",
    "",
    "https://i.postimg.cc/Rh3w9jtf/50.jpg",
    "https://i.postimg.cc/76ZgtCYK/51.jpg",
    "https://i.postimg.cc/C1rb3FRS/52.jpg",
    "",
    "https://i.postimg.cc/mr1DLC2c/ESN-Catacombs-12.jpg",
    "https://i.postimg.cc/Jz20CPmV/ESN-Catacombs-16.jpg",
    "https://i.postimg.cc/RZFhY2kL/ESN-Catacombs-20.jpg",
    "https://i.postimg.cc/8PwstT0C/ESN-Catacombs-23.jpg",
    "https://i.postimg.cc/kGJqbb9v/IMG-20220225-133517.jpg",
    "https://i.postimg.cc/fRk5xGn0/IMG-20220225-133457.png",
    "https://i.postimg.cc/T2FPdm2M/53.jpg",
    "https://i.postimg.cc/rmppmNtc/54.jpg",
    "https://i.postimg.cc/rs0FGyJP/55.jpg",
    "https://i.postimg.cc/3RbxD0gG/56.jpg",
    "https://i.postimg.cc/6qk6Msb5/57.jpg",
    "https://i.postimg.cc/NM8ZW30j/ESN-Catacombs-47.png",
    "https://i.postimg.cc/445rwRM8/ESN-Catacombs-8.png",
    "https://i.postimg.cc/90WsVL4t/ESN-Catacombs-9.png",
    "https://i.postimg.cc/mDV83BDC/ESN-Catacombs-5.jpg",
    "https://i.postimg.cc/2SvGc4yz/58.jpg",
    "https://i.postimg.cc/SNnD80pY/59.jpg",
    "https://i.postimg.cc/Pr0KQ6t3/60.jpg",
    "https://i.postimg.cc/VsGKdf2c/61.jpg",
    "",
    "https://i.postimg.cc/9FF1sWCk/62.jpg",
    "https://i.postimg.cc/RVsGBj0Z/63.jpg",
    "https://i.postimg.cc/3xk1JnyC/64.jpg",
    "https://i.postimg.cc/j2vcC1Qv/65.jpg",
    "https://i.postimg.cc/wvX0YM1C/66.jpg",
    "https://i.postimg.cc/85QtYMzd/67.jpg",
    "https://i.postimg.cc/T1TQdxmp/68.jpg",
    "https://i.postimg.cc/kMyfjV38/69.jpg",
    "",
    "https://i.postimg.cc/dVXhw9dC/DSC-0022.jpg",
    "https://i.postimg.cc/Kzh4gv0v/DSC-0054.png",
    "https://i.postimg.cc/W1tdByDj/DSC-0060.jpg",
    "https://i.postimg.cc/rFfdYTwQ/DSC-0068.jpg",
    "https://i.postimg.cc/pr2TqcNw/DSC-0073.jpg",
    "https://i.postimg.cc/sXPxPdLP/DSC-0087-1.jpg",
    "https://i.postimg.cc/vmVcB6LN/DSC-0147.jpg",
    "https://i.postimg.cc/mk8rq3Bt/DSC-0162.jpg",
    "https://i.postimg.cc/N0nG1Gbr/IMG-20240712-WA0014.png",
    "https://i.postimg.cc/jdMpWgMD/70.jpg",
    "https://i.postimg.cc/pLygKfSq/71.jpg",
    "https://i.postimg.cc/BbqzbHD5/DSC-0389.jpg",
    "https://i.postimg.cc/L5Nb15Bc/DSC-0390.jpg",
    "https://i.postimg.cc/1t0TyJg5/DSC-0391.jpg",
    "https://i.postimg.cc/76rdvpZW/DSC-0392.jpg",
    "https://i.postimg.cc/3x6z1y57/DSC-0394.jpg",
    "https://i.postimg.cc/KYMwHZxT/DSC-0403.jpg",
];
var indiceSerbia = 1;
var pantallaSerbia = document.getElementById('ver-serbia');
var imgSerbia = document.createElement("img");
var iframeSerbia = document.createElement("iframe");

//-- Ctes.
const totalSerbia = 122;

function mostrarSerbia(auxSerbia) {
    
    //-- Limpiar la pantalla.
    pantallaSerbia.innerHTML = "";

    //-- Verificar si es una imagen o un vídeo.
    if(imagenesIDserbia[auxSerbia-1]) {
        imgSerbia.src = imagenesIDserbia[auxSerbia-1];
        pantallaSerbia.appendChild(imgSerbia);
    }else {
        iframeSerbia.src = videosIDserbia[auxSerbia-1];
        iframeSerbia.width = "400";
        iframeSerbia.height = "533";
        iframeSerbia.setAttribute("allow", "autoplay");
        iframeSerbia.setAttribute("allowFullscreen", "false");
        pantallaSerbia.appendChild(iframeSerbia);
    }
}

function imgAnteriorSerbia() {
    if(indiceSerbia > 1) {
        indiceSerbia--;
    }else {
        indiceSerbia = totalSerbia;
    }
    mostrarSerbia(indiceSerbia);
}

function imgSiguienteSerbia() {
    if(indiceSerbia < totalSerbia) {
        indiceSerbia++;
    }else {
        indiceSerbia = 1;
    }
    mostrarSerbia(indiceSerbia);
}

//-- Pulsar flecha izquierda.
document.getElementById("izq-serbia").addEventListener("click", imgAnteriorSerbia);
//-- Pulsar flecha derecha.
document.getElementById("der-serbia").addEventListener("click", imgSiguienteSerbia);

//-- Punto de inicio del programa.
mostrarSerbia(indiceSerbia);