/*
{ type: "image", src: "" },
{ type: "youtube", src: "https://www.youtube.com/embed/" },
*/
const media =
[
  { type: "image", src: "https://i.postimg.cc/6p1p8vD9/1.jpg"},
  { type: "image", src: "https://i.postimg.cc/CKBLkKgb/2.jpg"},
  { type: "image", src: "https://i.postimg.cc/9QffXpg8/3.jpg"},
  { type: "image", src: "https://i.postimg.cc/j5YKfQvr/6.jpg"},
  { type: "image", src: "https://i.postimg.cc/nLJRvt0R/7.jpg"},
  { type: "image", src: "https://i.postimg.cc/hv6MhFX0/4.jpg"},
  { type: "image", src: "https://i.postimg.cc/bNS3Wv5V/5.jpg"},
  { type: "image", src: "https://i.postimg.cc/mgbVDSDJ/8.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/WwLNX99kb6A"},
  { type: "image", src: "https://i.postimg.cc/L6VBrZTT/9.jpg"},
  { type: "image", src: "https://i.postimg.cc/mr2J3PjZ/10.jpg"},
  { type: "image", src: "https://i.postimg.cc/857Y3xxq/11.jpg"},
  { type: "image", src: "https://i.postimg.cc/FKWqThCy/12.jpg"},
  { type: "image", src: "https://i.postimg.cc/VkzV1J39/DSC-0315.jpg"},
  { type: "image", src: "https://i.postimg.cc/Fs56WWpB/DSC-0344.jpg"},
  { type: "image", src: "https://i.postimg.cc/VvMVsnfg/DSC-0345.jpg"},
  { type: "image", src: "https://i.postimg.cc/SN6vw6tN/DSC-0348.jpg"},
  { type: "image", src: "https://i.postimg.cc/G3sNjwFD/DSC-0350.jpg"},
  { type: "image", src: "https://i.postimg.cc/rySqVYhS/13.jpg"},
  { type: "image", src: "https://i.postimg.cc/NfBB57VZ/14.jpg"},
  { type: "image", src: "https://i.postimg.cc/52rhqw74/IMG-9124.jpg"},
  { type: "image", src: "https://i.postimg.cc/Fznp5xJ1/15.jpg"},
  { type: "image", src: "https://i.postimg.cc/hjsMMnDL/16.jpg"},
  { type: "image", src: "https://i.postimg.cc/7PBm2qQD/17.jpg"},
  { type: "image", src: "https://i.postimg.cc/sx2mNLxt/18.jpg"},
  { type: "image", src: "https://i.postimg.cc/DzKgT0mQ/19.jpg"},
  { type: "image", src: "https://i.postimg.cc/Yqh8NTJF/20.jpg"},
  { type: "image", src: "https://i.postimg.cc/L6wDxNpb/21.jpg"},
  { type: "image", src: "https://i.postimg.cc/GmDQVG3h/22.jpg"},
  { type: "image", src: "https://i.postimg.cc/xdyPTQbw/23.jpg"},
  { type: "image", src: "https://i.postimg.cc/C1hsR2Gz/24.jpg"},
  { type: "image", src: "https://i.postimg.cc/50sqLmgp/25.jpg"},
  { type: "image", src: "https://i.postimg.cc/5yj53FkJ/26.jpg"},
  { type: "image", src: "https://i.postimg.cc/vTjrSHpV/27.jpg"},
  { type: "image", src: "https://i.postimg.cc/59kStn62/28.jpg"},
  { type: "image", src: "https://i.postimg.cc/9F7ZQ26L/29.jpg"},
  { type: "image", src: "https://i.postimg.cc/9QP9ypFT/30.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/Z25Z1l-sFmI"},
  { type: "image", src: "https://i.postimg.cc/YCBg4VkM/31.jpg"},
  { type: "image", src: "https://i.postimg.cc/HxZQQ5F4/32.jpg"},
  { type: "image", src: "https://i.postimg.cc/ZqSpmzW1/33.png"},
  { type: "image", src: "https://i.postimg.cc/6q8CzqXs/34.jpg"},
  { type: "image", src: "https://i.postimg.cc/RFV76GpZ/35.jpg"},
  { type: "image", src: "https://i.postimg.cc/Ghsky4KG/36.jpg"},
  { type: "image", src: "https://i.postimg.cc/jq1H2HHR/37.jpg"},
  { type: "image", src: "https://i.postimg.cc/g2F3qGt5/38.jpg"},
  { type: "image", src: "https://i.postimg.cc/nzzmcrMs/39.jpg"},
  { type: "image", src: "https://i.postimg.cc/wMRsLrXg/40.jpg"},
  { type: "image", src: "https://i.postimg.cc/NLh24xDT/41.jpg"},
  { type: "image", src: "https://i.postimg.cc/QtyTBDWf/42.jpg"},
  { type: "image", src: "https://i.postimg.cc/FHc3wHHy/43.png"},
  { type: "image", src: "https://i.postimg.cc/2j1H08T8/44.jpg"},
  { type: "image", src: "https://i.postimg.cc/zGFXLyDX/IMG-9241.jpg"},
  { type: "image", src: "https://i.postimg.cc/DwTwyrTM/IMG-9461.jpg"},
  { type: "image", src: "https://i.postimg.cc/Qx5M36R7/IMG-9476.jpg"},
  { type: "image", src: "https://i.postimg.cc/Y2TSTcyk/IMG-9542.jpg"},
  { type: "image", src: "https://i.postimg.cc/ryDmhyjQ/IMG-9543.jpg"},
  { type: "image", src: "https://i.postimg.cc/5yhDgSgd/IMG-9676.jpg"},
  { type: "image", src: "https://i.postimg.cc/qqh9258x/IMG-9742.jpg"},
  { type: "image", src: "https://i.postimg.cc/LsvKSf9L/IMG-9743.jpg"},
  { type: "image", src: "https://i.postimg.cc/tTmKZjVg/IMG-9892.jpg"},
  { type: "image", src: "https://i.postimg.cc/G220m2tN/IMG-9903.jpg"},
  { type: "image", src: "https://i.postimg.cc/3wwBVDdk/45.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/W1Obgu2YlcQ"},
  { type: "image", src: "https://i.postimg.cc/MKW6jyHM/46.jpg"},
  { type: "image", src: "https://i.postimg.cc/m28b3t1d/47.jpg"},
  { type: "image", src: "https://i.postimg.cc/xjGjCsfV/48.jpg"},
  { type: "image", src: "https://i.postimg.cc/W1zs5TMs/49.jpg"},
  { type: "image", src: "https://i.postimg.cc/tRBf2PDV/IMG-20220224-201126.png"},
  { type: "image", src: "https://i.postimg.cc/jdsfdnrv/DSCF1421.jpg"},
  { type: "image", src: "https://i.postimg.cc/Vs9M8B2d/PSX-20220225-211041.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/NNAAGDnMwMY"},
  { type: "image", src: "https://i.postimg.cc/Rh3w9jtf/50.jpg"},
  { type: "image", src: "https://i.postimg.cc/76ZgtCYK/51.jpg"},
  { type: "image", src: "https://i.postimg.cc/C1rb3FRS/52.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/E7d913JBHFg"},
  { type: "image", src: "https://i.postimg.cc/mr1DLC2c/ESN-Catacombs-12.jpg"},
  { type: "image", src: "https://i.postimg.cc/Jz20CPmV/ESN-Catacombs-16.jpg"},
  { type: "image", src: "https://i.postimg.cc/RZFhY2kL/ESN-Catacombs-20.jpg"},
  { type: "image", src: "https://i.postimg.cc/8PwstT0C/ESN-Catacombs-23.jpg"},
  { type: "image", src: "https://i.postimg.cc/kGJqbb9v/IMG-20220225-133517.jpg"},
  { type: "image", src: "https://i.postimg.cc/fRk5xGn0/IMG-20220225-133457.png"},
  { type: "image", src: "https://i.postimg.cc/T2FPdm2M/53.jpg"},
  { type: "image", src: "https://i.postimg.cc/rmppmNtc/54.jpg"},
  { type: "image", src: "https://i.postimg.cc/rs0FGyJP/55.jpg"},
  { type: "image", src: "https://i.postimg.cc/3RbxD0gG/56.jpg"},
  { type: "image", src: "https://i.postimg.cc/6qk6Msb5/57.jpg"},
  { type: "image", src: "https://i.postimg.cc/NM8ZW30j/ESN-Catacombs-47.png"},
  { type: "image", src: "https://i.postimg.cc/445rwRM8/ESN-Catacombs-8.png"},
  { type: "image", src: "https://i.postimg.cc/90WsVL4t/ESN-Catacombs-9.png"},
  { type: "image", src: "https://i.postimg.cc/mDV83BDC/ESN-Catacombs-5.jpg"},
  { type: "image", src: "https://i.postimg.cc/2SvGc4yz/58.jpg"},
  { type: "image", src: "https://i.postimg.cc/SNnD80pY/59.jpg"},
  { type: "image", src: "https://i.postimg.cc/Pr0KQ6t3/60.jpg"},
  { type: "image", src: "https://i.postimg.cc/VsGKdf2c/61.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/VCq5uBjleLQ"},
  { type: "image", src: "https://i.postimg.cc/9FF1sWCk/62.jpg"},
  { type: "image", src: "https://i.postimg.cc/RVsGBj0Z/63.jpg"},
  { type: "image", src: "https://i.postimg.cc/3xk1JnyC/64.jpg"},
  { type: "image", src: "https://i.postimg.cc/j2vcC1Qv/65.jpg"},
  { type: "image", src: "https://i.postimg.cc/wvX0YM1C/66.jpg"},
  { type: "image", src: "https://i.postimg.cc/85QtYMzd/67.jpg"},
  { type: "image", src: "https://i.postimg.cc/T1TQdxmp/68.jpg"},
  { type: "image", src: "https://i.postimg.cc/kMyfjV38/69.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/rd4ynoeNLjc"},
  { type: "image", src: "https://i.postimg.cc/dVXhw9dC/DSC-0022.jpg"},
  { type: "image", src: "https://i.postimg.cc/Kzh4gv0v/DSC-0054.png"},
  { type: "image", src: "https://i.postimg.cc/W1tdByDj/DSC-0060.jpg"},
  { type: "image", src: "https://i.postimg.cc/rFfdYTwQ/DSC-0068.jpg"},
  { type: "image", src: "https://i.postimg.cc/pr2TqcNw/DSC-0073.jpg"},
  { type: "image", src: "https://i.postimg.cc/sXPxPdLP/DSC-0087-1.jpg"},
  { type: "image", src: "https://i.postimg.cc/vmVcB6LN/DSC-0147.jpg"},
  { type: "image", src: "https://i.postimg.cc/mk8rq3Bt/DSC-0162.jpg"},
  { type: "image", src: "https://i.postimg.cc/N0nG1Gbr/IMG-20240712-WA0014.png"},
  { type: "image", src: "https://i.postimg.cc/jdMpWgMD/70.jpg"},
  { type: "image", src: "https://i.postimg.cc/pLygKfSq/71.jpg"},
  { type: "image", src: "https://i.postimg.cc/BbqzbHD5/DSC-0389.jpg"},
  { type: "image", src: "https://i.postimg.cc/L5Nb15Bc/DSC-0390.jpg"},
  { type: "image", src: "https://i.postimg.cc/1t0TyJg5/DSC-0391.jpg"},
  { type: "image", src: "https://i.postimg.cc/76rdvpZW/DSC-0392.jpg"},
  { type: "image", src: "https://i.postimg.cc/3x6z1y57/DSC-0394.jpg"},
  { type: "image", src: "https://i.postimg.cc/KYMwHZxT/DSC-0403.jpg"},
  { type: "image", src: "https://i.postimg.cc/xTfgBLKY/72.jpg"},
  { type: "image", src: "https://i.postimg.cc/vBPsRf0K/IMG-20220303-132716.png"},
  { type: "image", src: "https://i.postimg.cc/KjRymjV8/IMG-20220303-133925.png"},
  { type: "image", src: "https://i.postimg.cc/zv6Yv5ZS/IMG-20220303-133932.png"},
  { type: "image", src: "https://i.postimg.cc/NMFnHVxN/IMG-20220303-133947.png"},
  { type: "image", src: "https://i.postimg.cc/xCZ4yRx9/IMG-20220307-212426.png"},
  { type: "image", src: "https://i.postimg.cc/gJfPkmPy/IMG-20220308-222430.png"},
  { type: "image", src: "https://i.postimg.cc/g0TCNmr9/IMG-20220304-WA0008.png"},
  { type: "image", src: "https://i.postimg.cc/3R2tmTvF/73.jpg"},
  { type: "image", src: "https://i.postimg.cc/Y2fXStkp/74.jpg"},
  { type: "image", src: "https://i.postimg.cc/Zncjsxj9/75.jpg"},
  { type: "image", src: "https://i.postimg.cc/mkR8S53f/76.jpg"},
  { type: "image", src: "https://i.postimg.cc/BQSmLRQ2/77.jpg"},
  { type: "image", src: "https://i.postimg.cc/52jppvz0/78.jpg"},
  { type: "image", src: "https://i.postimg.cc/GhXqkzHV/79.jpg"},
  { type: "image", src: "https://i.postimg.cc/nhvrySBw/80.jpg"},
  { type: "image", src: "https://i.postimg.cc/TPf1fjc2/81.jpg"},
  { type: "image", src: "https://i.postimg.cc/FFnK3vd2/ESN-Karlovci-26.jpg"},
  { type: "image", src: "https://i.postimg.cc/ZRbqFKLh/ESN-Karlovci-27.jpg"},
  { type: "image", src: "https://i.postimg.cc/q7LJRHHD/ESN-Karlovci-30.jpg"},
  { type: "image", src: "https://i.postimg.cc/xTwTpPP5/ESN-Karlovci-40.jpg"},
  { type: "image", src: "https://i.postimg.cc/L8j4cZCp/ESN-Karlovci-44.jpg"},
  { type: "image", src: "https://i.postimg.cc/2jJz3xgY/ESN-Karlovci-6.jpg"},
  { type: "image", src: "https://i.postimg.cc/d0vQwtpT/ESN-Karlovci-7.jpg"},
  { type: "image", src: "https://i.postimg.cc/cCVZjsfC/ESN-Karlovci-8.jpg"},
  { type: "image", src: "https://i.postimg.cc/qRvk6DkJ/IMG-20220306-WA0000.jpg"},
  { type: "image", src: "https://i.postimg.cc/SQGvvQ7v/ESN-Karlovci-45.jpg"},
  { type: "image", src: "https://i.postimg.cc/MHzrpgx5/ESN-Karlovci-48.jpg"},
  { type: "image", src: "https://i.postimg.cc/gj4tX42W/ESN-Karlovci-49.jpg"},
  { type: "image", src: "https://i.postimg.cc/DwVmY3JX/82.jpg"},
  { type: "image", src: "https://i.postimg.cc/SKdssXZ6/83.jpg"},
  { type: "image", src: "https://i.postimg.cc/Jh1fnyqZ/ESN-Karlovci-52.jpg"},
  { type: "image", src: "https://i.postimg.cc/0ydgPGp9/ESN-Karlovci-54.jpg"},
  { type: "image", src: "https://i.postimg.cc/4xTCD2H8/ESN-Karlovci-60.jpg"},
  { type: "image", src: "https://i.postimg.cc/hhRzmkVT/IMG-20220305-222821.png"},
  { type: "image", src: "https://i.postimg.cc/1RwGHS3L/84.jpg"},
  { type: "image", src: "https://i.postimg.cc/mrK9YpfL/IMG-20220306-140143.png"},
  { type: "youtube", src: "https://www.youtube.com/embed/13b_Riw1aQw"},
  { type: "image", src: "https://i.postimg.cc/j2p3B47t/85.jpg"},
  { type: "image", src: "https://i.postimg.cc/DfSvkfXM/86.jpg"},
  { type: "image", src: "https://i.postimg.cc/gc1YY9yk/87.jpg"},
  { type: "image", src: "https://i.postimg.cc/ZK3JnfjP/88.jpg"},
  { type: "image", src: "https://i.postimg.cc/QdJskH2H/89.jpg"},
  { type: "image", src: "https://i.postimg.cc/sgrshp0k/90.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/8R5jpNnIkaM"},
  { type: "image", src: "https://i.postimg.cc/KY5zz9Gp/91.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/Lj8e5AtT1sM"},
  { type: "image", src: "https://i.postimg.cc/4yXtFK8n/92.jpg"},
  { type: "image", src: "https://i.postimg.cc/FRy3ZbV2/93.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/V_Qd2HpAlv4"},
  { type: "image", src: "https://i.postimg.cc/x8WQ1mW1/94.jpg"},
  { type: "image", src: "https://i.postimg.cc/sf8smFvC/IMG-20220314-093232.png"},
  { type: "image", src: "https://i.postimg.cc/d3nWWc9P/95.jpg"},
  { type: "image", src: "https://i.postimg.cc/BbJYcnHB/96.jpg"},
  { type: "image", src: "https://i.postimg.cc/3rLCb1TT/IMG-20220324-184532.jpg"},
  { type: "image", src: "https://i.postimg.cc/yxrmg1Pd/IMG-20220324-184535.jpg"},
  { type: "image", src: "https://i.postimg.cc/sx2PgQ5q/IMG-20220324-184544.jpg"},
  { type: "image", src: "https://i.postimg.cc/vBhLyLx5/IMG-20220324-184609.jpg"},
  { type: "image", src: "https://i.postimg.cc/pTRY31r2/IMG-20220324-184800.jpg"},
  { type: "image", src: "https://i.postimg.cc/SKWfTpyT/IMG-20220324-184811.jpg"},
  { type: "image", src: "https://i.postimg.cc/0Ncb2tZ5/97.jpg"},
  { type: "image", src: "https://i.postimg.cc/bJrdGQFx/98.jpg"},
  { type: "image", src: "https://i.postimg.cc/G2T87FJc/IMG-20220327-132621.jpg"},
  { type: "image", src: "https://i.postimg.cc/hG5Q1ymy/IMG-20220327-132724.jpg"},
  { type: "image", src: "https://i.postimg.cc/tTmTjYkB/IMG-20220327-134011.png"},
  { type: "image", src: "https://i.postimg.cc/SR2KNktk/IMG-20220327-134155.png"},
  { type: "image", src: "https://i.postimg.cc/XJvJmwfZ/IMG-20220327-134815.png"},
  { type: "image", src: "https://i.postimg.cc/Kj681wdL/IMG-20220327-134857.png"},
  { type: "image", src: "https://i.postimg.cc/YCnqg4KM/99.jpg"},
  { type: "image", src: "https://i.postimg.cc/Dwyw8rNx/100.jpg"},
  { type: "image", src: "https://i.postimg.cc/QMFNqXh5/101.jpg"},
  { type: "image", src: "https://i.postimg.cc/HW9cS4ft/IMG-20220412-194000.jpg"},
  { type: "image", src: "https://i.postimg.cc/C1YMD9Lp/IMG-20220412-194023.jpg"},
  { type: "image", src: "https://i.postimg.cc/rps3HJnR/IMG-20220329-153107.png"},
  { type: "image", src: "https://i.postimg.cc/9FXp1fNr/102.jpg"},
  { type: "image", src: "https://i.postimg.cc/pLpBb6vv/103.jpg"},
  { type: "image", src: "https://i.postimg.cc/qvSxkxB3/104.jpg"},
  { type: "image", src: "https://i.postimg.cc/rFh9HLvg/105.jpg"},
  { type: "image", src: "https://i.postimg.cc/7Y723rqf/IMG-20220402-211354.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/_yc4wWjVS_k"},
  { type: "image", src: "https://i.postimg.cc/X7jwNsRr/IMG-20220404-WA0004.png"},
  { type: "image", src: "https://i.postimg.cc/ZYF8hGMk/IMG-20220329-224800.png"},
  { type: "image", src: "https://i.postimg.cc/63CmKMDH/113.jpg"},
  { type: "image", src: "https://i.postimg.cc/N03zZ3P9/114.jpg"},
  { type: "image", src: "https://i.postimg.cc/13YTrnGK/115.jpg"},
  { type: "image", src: "https://i.postimg.cc/g0X7Sz4b/116.jpg"},
  { type: "image", src: "https://i.postimg.cc/sxy0gpz3/117.jpg"},
  { type: "image", src: "https://i.postimg.cc/QdxkSjhN/IMG-20220424-184458.jpg"},
  { type: "image", src: "https://i.postimg.cc/wjf5GnjX/IMG-20220424-185745.jpg"},
  { type: "image", src: "https://i.postimg.cc/rpDGXgDv/IMG-20220424-185755.jpg"},
  { type: "image", src: "https://i.postimg.cc/SKY9ts54/106.jpg"},
  { type: "image", src: "https://i.postimg.cc/FRtStv5L/107.jpg"},
  { type: "image", src: "https://i.postimg.cc/wvhmgrgb/108.jpg"},
  { type: "image", src: "https://i.postimg.cc/Zn4yRLqY/109.jpg"},
  { type: "image", src: "https://i.postimg.cc/mZyHnKdP/110.jpg"},
  { type: "image", src: "https://i.postimg.cc/8c4frrFR/111.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/GFfUwzTK5yM"},
  { type: "youtube", src: "https://www.youtube.com/embed/_4a_hRU9wG4"},
  { type: "image", src: "https://i.postimg.cc/SNVtmTKs/112.jpg"},
  { type: "image", src: "https://i.postimg.cc/4d7TcCmB/IMG-20220415-104432.png"},
  { type: "image", src: "https://i.postimg.cc/prKb0DQj/IMG-20220415-133412.png"},
  { type: "image", src: "https://i.postimg.cc/Yq1CfNLN/118.png"},
  { type: "image", src: "https://i.postimg.cc/6pWtrkXw/119.jpg"},
  { type: "image", src: "https://i.postimg.cc/Przd8t02/120.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/XYy2-g1fnRg"},
  { type: "image", src: "https://i.postimg.cc/N0XJ50z0/121.jpg"},
  { type: "image", src: "https://i.postimg.cc/Mp5RtJfY/122.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/2Pa1qCsUI1Q"},
  { type: "image", src: "https://i.postimg.cc/dt8Gkyqp/123.jpg"},
  { type: "image", src: "https://i.postimg.cc/0yPDpyjQ/124.jpg"},
  { type: "image", src: "https://i.postimg.cc/Pq8XJmH8/IMG-20220501-192140.jpg"},
  { type: "image", src: "https://i.postimg.cc/Gmf3bXWC/IMG-20220501-192315.jpg"},
  { type: "image", src: "https://i.postimg.cc/3xzhsdGr/125.jpg"},
  { type: "image", src: "https://i.postimg.cc/DyjncCyX/126.jpg"},
  { type: "image", src: "https://i.postimg.cc/0yzxXpbH/127.jpg"},
  { type: "image", src: "https://i.postimg.cc/Gh3w56Mp/IMG-3547.png"},
  { type: "image", src: "https://i.postimg.cc/0Q1hd4MP/IMG-3546.png"},
  { type: "image", src: "https://i.postimg.cc/j2g8935W/IMG-3541.jpg"},
  { type: "image", src: "https://i.postimg.cc/vTHq0wQF/IMG-3470.jpg"},
  { type: "image", src: "https://i.postimg.cc/2j2XVywz/IMG-3490.jpg"},
  { type: "image", src: "https://i.postimg.cc/PxcpRmHX/IMG-3538.png"},
  { type: "image", src: "https://i.postimg.cc/vm065JS6/IMG-3540.png"},
  { type: "image", src: "https://i.postimg.cc/q7J3hJQT/IMG-3536.png"},
  { type: "image", src: "https://i.postimg.cc/jSQfSwHc/IMG-3533.png"},
  { type: "image", src: "https://i.postimg.cc/0QrKnVLX/IMG-3530.png"},
  { type: "image", src: "https://i.postimg.cc/wjdJzcm3/IMG-3527.png"},
  { type: "image", src: "https://i.postimg.cc/VLtM2H53/IMG-3525.png"},
  { type: "image", src: "https://i.postimg.cc/bYWkCjYx/IMG-3523.png"},
  { type: "image", src: "https://i.postimg.cc/J0fXGjY6/IMG-3521.png"},
  { type: "image", src: "https://i.postimg.cc/8cJWpZ4f/IMG-3520.png"},
  { type: "image", src: "https://i.postimg.cc/xCFMVwvS/IMG-3514.png"},
  { type: "image", src: "https://i.postimg.cc/Bvp2MLtb/IMG-3508.png"},
  { type: "image", src: "https://i.postimg.cc/xdnKvyfB/IMG-3504.png"},
  { type: "image", src: "https://i.postimg.cc/xCdM7fbR/IMG-3486.png"},
  { type: "image", src: "https://i.postimg.cc/2S4QLXD4/IMG-3482.png"},
  { type: "image", src: "https://i.postimg.cc/DwVQZ3tv/IMG-3473.png"},
  { type: "image", src: "https://i.postimg.cc/BQPc4n77/IMG-3461.png"},
  { type: "image", src: "https://i.postimg.cc/d3p2rb39/IMG-3450.png"},
  { type: "image", src: "https://i.postimg.cc/SsZ7N2p3/IMG-3449.png"},
  { type: "image", src: "https://i.postimg.cc/d3LR7ss1/IMG-3420.png"},
  { type: "image", src: "https://i.postimg.cc/wxyfqm2L/128.jpg"},
  { type: "image", src: "https://i.postimg.cc/fLkH0tN4/129.jpg"},
  { type: "image", src: "https://i.postimg.cc/hjwCnqNt/IMG-20220505-164400.png"},
  { type: "image", src: "https://i.postimg.cc/4dMWvffY/130.jpg"},
  { type: "image", src: "https://i.postimg.cc/qq3jjPqj/131.jpg"},
  { type: "image", src: "https://i.postimg.cc/WpB9h1YK/132.jpg"},
  { type: "image", src: "https://i.postimg.cc/Qxcf5ZRM/133.jpg"},
  { type: "image", src: "https://i.postimg.cc/jSKZ4kb4/134.jpg"},
  { type: "image", src: "https://i.postimg.cc/k4gs8HFd/IMG-20220505-185203.jpg"},
  { type: "image", src: "https://i.postimg.cc/qRCsT8r7/135.jpg"},
  { type: "image", src: "https://i.postimg.cc/nr4qspCb/136.jpg"},
  { type: "image", src: "https://i.postimg.cc/sDzYhXPR/IMG-20220506-022913.jpg"},
  { type: "image", src: "https://i.postimg.cc/sgD5TN06/IMG-20220505-194101.jpg"},
  { type: "image", src: "https://i.postimg.cc/0yWDF0T8/IMG-20220505-194105.jpg"},
  { type: "image", src: "https://i.postimg.cc/wTkhcpFR/IMG-20220505-194112.jpg"},
  { type: "image", src: "https://i.postimg.cc/QCGpxHNJ/137.jpg"},
  { type: "image", src: "https://i.postimg.cc/k5HQzTkZ/138.jpg"},
  { type: "image", src: "https://i.postimg.cc/rskr23gh/IMG-20220505-200432.jpg"},
  { type: "image", src: "https://i.postimg.cc/cL26NPLQ/139.jpg"},
  { type: "image", src: "https://i.postimg.cc/nhCMgnpF/140.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/BrokraUMsUY"},
  { type: "image", src: "https://i.postimg.cc/mk9FCkFd/DSC-0896.png"},
  { type: "image", src: "https://i.postimg.cc/cH2nvw6g/IMG-20220507-104343.png"},
  { type: "image", src: "https://i.postimg.cc/NF2qWjLv/IMG-20220507-104036.png"},
  { type: "image", src: "https://i.postimg.cc/W3BdNVf0/DSCF1682.jpg"},
  { type: "image", src: "https://i.postimg.cc/2SrBLzjw/DSC-0861.jpg"},
  { type: "image", src: "https://i.postimg.cc/PrmwqLHJ/DSC-0865-1.jpg"},
  { type: "image", src: "https://i.postimg.cc/7YvzD3pj/DSC-0866.jpg"},
  { type: "image", src: "https://i.postimg.cc/7Z9Jgpfy/DSC-0868.jpg"},
  { type: "image", src: "https://i.postimg.cc/Gpp8zqyT/DSC-0871.jpg"},
  { type: "image", src: "https://i.postimg.cc/s20BL7Y6/DSC-0899.jpg"},
  { type: "image", src: "https://i.postimg.cc/LXYqF5vH/DSC-0912.jpg"},
  { type: "image", src: "https://i.postimg.cc/c4NvPs3S/IMG-20220507-114857.jpg"},
  { type: "image", src: "https://i.postimg.cc/WpZD9Dh8/IMG-20220507-114919.jpg"},
  { type: "image", src: "https://i.postimg.cc/L5jnhWrw/IMG-20220507-114947.jpg"},
  { type: "image", src: "https://i.postimg.cc/764RPd0C/DSC-0864.png"},
  { type: "image", src: "https://i.postimg.cc/QtqyFmJf/IMG-20220507-110302.png"},
  { type: "image", src: "https://i.postimg.cc/3rcZnzNg/DSCF1657.jpg"},
  { type: "image", src: "https://i.postimg.cc/85yb80Hg/DSCF1659.jpg"},
  { type: "image", src: "https://i.postimg.cc/ZKvxgjvX/DSCF1662.jpg"},
  { type: "image", src: "https://i.postimg.cc/WzC6zqC9/IMG-20220507-110306.jpg"},
  { type: "image", src: "https://i.postimg.cc/90rYcY8R/IMG-20220507-111122.jpg"},
  { type: "image", src: "https://i.postimg.cc/PxfMRj1M/IMG-20220507-111209.jpg"},
  { type: "image", src: "https://i.postimg.cc/PxBMyFQX/IMG-20220507-112130.png"},
  { type: "image", src: "https://i.postimg.cc/QMdSd7M3/DSC-0873.jpg"},
  { type: "image", src: "https://i.postimg.cc/BnsMRk9t/DSC-0875.jpg"},
  { type: "image", src: "https://i.postimg.cc/m27mXRn0/DSC-0876.jpg"},
  { type: "image", src: "https://i.postimg.cc/BngM3p4p/DSC-0882.jpg"},
  { type: "image", src: "https://i.postimg.cc/TPN0LPyW/DSC-0890.jpg"},
  { type: "image", src: "https://i.postimg.cc/vB1zWd92/IMG-20220507-111432.jpg"},
  { type: "image", src: "https://i.postimg.cc/0QxkS9LP/DSCF1686.png"},
  { type: "image", src: "https://i.postimg.cc/W4VLWXS7/DSCF1676.png"},
  { type: "image", src: "https://i.postimg.cc/mgCWy03D/DSCF1678.png"},
  { type: "image", src: "https://i.postimg.cc/TYn3Bqgd/IMG-20220507-115205.png"},
  { type: "image", src: "https://i.postimg.cc/9X6fxN4g/IMG-20220507-114938.png"},
  { type: "image", src: "https://i.postimg.cc/4yyX8qVy/IMG-20220507-115212.jpg"},
  { type: "image", src: "https://i.postimg.cc/RFXML432/IMG-20220507-115412.jpg"},
  { type: "image", src: "https://i.postimg.cc/pT2WjpdD/IMG-20220507-115416.jpg"},
  { type: "image", src: "https://i.postimg.cc/BZhFq1Z9/DSC-0901.png"},
  { type: "image", src: "https://i.postimg.cc/BbwPNR7Q/IMG-20220507-130846.png"},
  { type: "image", src: "https://i.postimg.cc/DwG4djrn/DSC-0918.png"},
  { type: "image", src: "https://i.postimg.cc/mDLc4T0g/IMG-20220507-125305.png"},
  { type: "image", src: "https://i.postimg.cc/63q9zqkn/IMG-20220507-122631.jpg"},
  { type: "image", src: "https://i.postimg.cc/gJ7G7dp5/IMG-20220507-122836.jpg"},
  { type: "image", src: "https://i.postimg.cc/HLBYQXhT/IMG-20220507-122903.jpg"},
  { type: "image", src: "https://i.postimg.cc/LsH4YNvy/IMG-20220507-124242.jpg"},
  { type: "image", src: "https://i.postimg.cc/Bn5Qnd5L/IMG-20220507-124443.jpg"},
  { type: "image", src: "https://i.postimg.cc/hvHPXn3x/IMG-20220507-124519.jpg"},
  { type: "image", src: "https://i.postimg.cc/L8F8RHPF/IMG-20220507-125035.jpg"},
  { type: "image", src: "https://i.postimg.cc/hPdtHJf0/IMG-20220507-125045.jpg"},
  { type: "image", src: "https://i.postimg.cc/BZyvY5Q6/IMG-20220507-130130.jpg"},
  { type: "image", src: "https://i.postimg.cc/X7SrNcMP/1.jpg"},
  { type: "image", src: "https://i.postimg.cc/4xwy1DKC/DSCF1689.jpg"},
  { type: "image", src: "https://i.postimg.cc/yNddpL9D/DSCF1710.jpg"},
  { type: "image", src: "https://i.postimg.cc/HkTjXYk4/DSC-0931.jpg"},
  { type: "image", src: "https://i.postimg.cc/gkVnxXm2/DSC-0934.jpg"},
  { type: "image", src: "https://i.postimg.cc/4yZRq3MW/DSC-0943.png"},
  { type: "image", src: "https://i.postimg.cc/LscpkDVK/IMG-20220507-132329.jpg"},
  { type: "image", src: "https://i.postimg.cc/BZxqgryh/DSCF1679.jpg"},
  { type: "image", src: "https://i.postimg.cc/RV4vbPxv/DSCF1728.jpg"},
  { type: "image", src: "https://i.postimg.cc/jSjtRLj9/DSCF1730.jpg"},
  { type: "image", src: "https://i.postimg.cc/W1fjzTF4/DSCF1735.jpg"},
  { type: "image", src: "https://i.postimg.cc/nzqt3mds/DSCF1740.jpg"},
  { type: "image", src: "https://i.postimg.cc/X7LnMwnd/DSC-0940.jpg"},
  { type: "image", src: "https://i.postimg.cc/pXT6T8DD/IMG-20220507-163117.png"},
  { type: "image", src: "https://i.postimg.cc/3R1trJNS/IMG-20220507-163124.jpg"},
  { type: "image", src: "https://i.postimg.cc/ZR4fhybv/IMG-20220507-163151.jpg"},
  { type: "image", src: "https://i.postimg.cc/kMwHqwtJ/DSC-0957.jpg"},
  { type: "image", src: "https://i.postimg.cc/TY4HWw9B/DSC-0960.jpg"},
  { type: "image", src: "https://i.postimg.cc/90xgbFjR/DSC-0963.jpg"},
  { type: "image", src: "https://i.postimg.cc/GmTgPCgt/DSC-0964.jpg"},
  { type: "image", src: "https://i.postimg.cc/d08WX9YK/DSC-0966.jpg"},
  { type: "image", src: "https://i.postimg.cc/Gp07q56Q/DSC-0967.jpg"},
  { type: "image", src: "https://i.postimg.cc/Y0SbvKmp/DSC-0970.jpg"},
  { type: "image", src: "https://i.postimg.cc/nzr3zfmn/141.jpg"},
  { type: "image", src: "https://i.postimg.cc/RZxpTYkT/142.jpg"},
  { type: "image", src: "https://i.postimg.cc/pLQGcZxM/143.jpg"},
  { type: "image", src: "https://i.postimg.cc/vHVSfyNB/144.jpg"},
  { type: "image", src: "https://i.postimg.cc/LsHyc16Y/145.jpg"},
  { type: "image", src: "https://i.postimg.cc/SKDZkxJZ/146.jpg"},
  { type: "image", src: "https://i.postimg.cc/G2fqTgPG/147.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/XKNAKGtnbzs"},
  { type: "image", src: "https://i.postimg.cc/xCdbV0z3/148.jpg"},
  { type: "image", src: "https://i.postimg.cc/yxggWvnJ/149.jpg"},
  { type: "image", src: "https://i.postimg.cc/cH5tsV7y/150.jpg"},
  { type: "image", src: "https://i.postimg.cc/Rh6G1rv4/IMG-20220515-115511.jpg"},
  { type: "image", src: "https://i.postimg.cc/Kj6fJ9YL/IMG-20220515-115750.jpg"},
  { type: "image", src: "https://i.postimg.cc/RFbXnC5g/IMG-20220515-174843.jpg"},
  { type: "image", src: "https://i.postimg.cc/T2KXNpwY/IMG-20220516-122330-189.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/2yPqoN5wlEs"},
  { type: "youtube", src: "https://www.youtube.com/embed/ix60B8zJNvQ"},
  { type: "image", src: "https://i.postimg.cc/nzZsxgdT/151.jpg"},
  { type: "image", src: "https://i.postimg.cc/MH9WjKy3/IMG-20220521-WA0005.png"},
  { type: "youtube", src: "https://www.youtube.com/embed/_RBdMkYE2Bo"},
  { type: "image", src: "https://i.postimg.cc/WpKxWk5p/IMG-20220521-215117.jpg"},
  { type: "image", src: "https://i.postimg.cc/5yZG6hXQ/IMG-20220521-221302.jpg"},
  { type: "image", src: "https://i.postimg.cc/GhTndQ4s/IMG-20220523-091354-170.jpg"},
  { type: "image", src: "https://i.postimg.cc/pd11Gs8d/152.jpg"},
  { type: "image", src: "https://i.postimg.cc/0NL0KFD7/153.jpg"},
  { type: "image", src: "https://i.postimg.cc/tCtvQqPw/154.jpg"},
  { type: "image", src: "https://i.postimg.cc/TwLNZnqJ/155.jpg"},
  { type: "image", src: "https://i.postimg.cc/yxhjHjJc/156.jpg"},
  { type: "image", src: "https://i.postimg.cc/t4v5pYgS/157.jpg"},
  { type: "image", src: "https://i.postimg.cc/fW7fkHL0/158.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/oA6NSTdEYIY"},
  { type: "youtube", src: "https://www.youtube.com/embed/kgPnBCSDr0k"},
  { type: "image", src: "https://i.postimg.cc/zGCczhBF/159.jpg"},
  { type: "image", src: "https://i.postimg.cc/8kFD1yVd/IMG-20220602-220218.jpg"},
  { type: "image", src: "https://i.postimg.cc/gr9gdcb7/IMG-20220602-220223.jpg"},
  { type: "image", src: "https://i.postimg.cc/3Ry3k1zv/160.jpg"},
  { type: "image", src: "https://i.postimg.cc/vBpbf9dS/161.jpg"},
  { type: "image", src: "https://i.postimg.cc/s2gjrscK/162.jpg"},
  { type: "image", src: "https://i.postimg.cc/MG3WZN3w/163.jpg"},
  { type: "image", src: "https://i.postimg.cc/3Nm7BR8r/164.jpg"},
  { type: "image", src: "https://i.postimg.cc/wjtgF7Ph/IMG-20220611-WA0006.png"},
  { type: "image", src: "https://i.postimg.cc/52Z1rfdD/IMG-20220604-233230.png"},
  { type: "image", src: "https://i.postimg.cc/L6Qmzzy9/IMG-20220604-233302.png"},
  { type: "image", src: "https://i.postimg.cc/Wb12F9wY/IMG-20220612-010849.png"},
  { type: "image", src: "https://i.postimg.cc/Y23rScYm/IMG-20220617-192854.png"},
  { type: "image", src: "https://i.postimg.cc/ryhBbq5g/IMG-20220618-202812.png"},
  { type: "image", src: "https://i.postimg.cc/QCnvWqjv/IMG-20220618-204209.png"},
  { type: "image", src: "https://i.postimg.cc/2y5P6tN4/IMG-20220619-131444.png"},
  { type: "image", src: "https://i.postimg.cc/RhqD9nwd/165.jpg"},
  { type: "image", src: "https://i.postimg.cc/hvw3GPrB/166.jpg"},
  { type: "image", src: "https://i.postimg.cc/mDgdNFp4/IMG-20220623-191434.png"},
  { type: "image", src: "https://i.postimg.cc/VNRGCFR4/IMG-20220624-WA0015.png"},
  { type: "image", src: "https://i.postimg.cc/kgCLRDCJ/169.jpg"},
  { type: "image", src: "https://i.postimg.cc/Z5L28ZYr/170.jpg"},
  { type: "image", src: "https://i.postimg.cc/m2y8qjx4/IMG-20220626-WA0001.png"},
  { type: "image", src: "https://i.postimg.cc/2SHTj58X/171.jpg"},
  { type: "image", src: "https://i.postimg.cc/sXWJJ9Pt/IMG-20220626-192628.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/xt2H7tSxnR8"},
  { type: "youtube", src: "https://www.youtube.com/embed/KdgTZURbkqg"},
  { type: "youtube", src: "https://www.youtube.com/embed/QKUDZ-Cf-W4"},
  { type: "youtube", src: "https://www.youtube.com/embed/sXilsD6mPdc"},
  { type: "youtube", src: "https://www.youtube.com/embed/EN8YMMvim2k"},
  { type: "image", src: "https://i.postimg.cc/0N68cZW5/168.jpg"},
  { type: "image", src: "https://i.postimg.cc/pLcWf3B1/172.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/ZcKxNOJL2W8"},
  { type: "image", src: "https://i.postimg.cc/Y9Ytw0BJ/173.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/-zY8W2yccN0"},
  { type: "youtube", src: "https://www.youtube.com/embed/sSbzJMfy9VY"},
  { type: "youtube", src: "https://www.youtube.com/embed/1TrBzFUvmZM"},
  { type: "image", src: "https://i.postimg.cc/YSJtVgZ6/174.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/I21TMbzOOms"},
  { type: "youtube", src: "https://www.youtube.com/embed/AyM46arObOM"},
  { type: "youtube", src: "https://www.youtube.com/embed/SdfJXLRt_Rk"},
  { type: "image", src: "https://i.postimg.cc/dtqwzJHx/IMG-20220708-054254.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/9NPs0yC59pw"},
  { type: "image", src: "https://i.postimg.cc/xjG9xXRm/IMG-20220708-051814.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/jrYz2CZXAxs"},
  { type: "image", src: "https://i.postimg.cc/q7712C8C/IMG-20250909-235102-139.webp"},
  { type: "youtube", src: "https://www.youtube.com/embed/K8w2HbYvlBA"},
  { type: "youtube", src: "https://www.youtube.com/embed/fwjE8yqfWlo"},
  { type: "youtube", src: "https://www.youtube.com/embed/h8EIpf7hwms"},
  { type: "image", src: "https://i.postimg.cc/637hcTVT/177.jpg"},
  { type: "image", src: "https://i.postimg.cc/VvqnZtJs/IMG-20220710-WA0007.jpg"},
  { type: "image", src: "https://i.postimg.cc/NFqRxDfP/IMG-20220709-183320.jpg"},
  { type: "image", src: "https://i.postimg.cc/ryx1wBf6/IMG-20220711-012553.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/_8EJXoZqLP0"},
  { type: "youtube", src: "https://www.youtube.com/embed/fCRsbS2vxPQ"},
  { type: "image", src: "https://i.postimg.cc/Mp8CKD2x/178.jpg"},
  { type: "image", src: "https://i.postimg.cc/q7712C8C/IMG-20250909-235102-139.webp"},
  { type: "youtube", src: "https://www.youtube.com/embed/4BIG5hAQADE"},
  { type: "youtube", src: "https://www.youtube.com/embed/2ANGdlvDNww"},
  { type: "youtube", src: "https://www.youtube.com/embed/5HtqFRgUzWY"},
  { type: "youtube", src: "https://www.youtube.com/embed/_XZ8n0cK0YU"},
  { type: "youtube", src: "https://www.youtube.com/embed/b-tnQN80mA8"},
  { type: "youtube", src: "https://www.youtube.com/embed/-xoxemQjN3A"},
  { type: "youtube", src: "https://www.youtube.com/embed/w8ilEJ7mgDI"},
  { type: "youtube", src: "https://www.youtube.com/embed/UNRmGg0yl4U"},
  { type: "youtube", src: "https://www.youtube.com/embed/A0Qx9Qtnfak"},
  { type: "youtube", src: "https://www.youtube.com/embed/RUnU39xiyCs"},
  { type: "youtube", src: "https://www.youtube.com/embed/Ck58HQksLBA"},
  { type: "youtube", src: "https://www.youtube.com/embed/RiVdh-S8Caw"},
  { type: "image", src: "https://i.postimg.cc/L5ZFWjxh/176.jpg"},
  { type: "image", src: "https://i.postimg.cc/T308khTG/IMG-20250910-184452-320.webp"},
  { type: "youtube", src: "https://www.youtube.com/embed/B4Ljo99DXTE"},
  { type: "image", src: "https://i.postimg.cc/qBNVmqxf/IMG-20220716-235032.png"},
  { type: "youtube", src: "https://www.youtube.com/embed/okJZEDq1ICA"},
  { type: "image", src: "https://i.postimg.cc/gJ6vRQdZ/IMG-20220711-145316-490.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/ngaD3HHvX7Y"},
  { type: "youtube", src: "https://www.youtube.com/embed/Fk6q3v7lxWc"},
  { type: "youtube", src: "https://www.youtube.com/embed/lBLiVldiBVU"},
  { type: "youtube", src: "https://www.youtube.com/embed/ePEoDq92bgg"},
  { type: "youtube", src: "https://www.youtube.com/embed/mTboPjXfPLI"},
  { type: "youtube", src: "https://www.youtube.com/embed/R0XFfv8BnoA"},
  { type: "image", src: "https://i.postimg.cc/v8tHsc64/181.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/PGYMOUOkHeI"},
  { type: "image", src: "https://i.postimg.cc/7b8rrbR9/175.jpg"},
  { type: "image", src: "https://i.postimg.cc/52tWdc7Z/IMG-20220711-062011.jpg"},
  { type: "image", src: "https://i.postimg.cc/CLDyg22m/179.jpg"},
  { type: "image", src: "https://i.postimg.cc/CxHWZqS8/182.jpg"},
  { type: "image", src: "https://i.postimg.cc/zB3MP2Ww/180.jpg"},
  { type: "image", src: "https://i.postimg.cc/pT77NQYw/SAVE-20220711-143834.jpg"},
  { type: "image", src: "https://i.postimg.cc/x8zZ9k6c/SAVE-20220711-143842.jpg"},
  { type: "image", src: "https://i.postimg.cc/SNbTWxZf/183.jpg"},
  { type: "image", src: "https://i.postimg.cc/QNTY9TqM/184.jpg"},
  { type: "image", src: "https://i.postimg.cc/L8C309V7/IMG-20220720-090243.png"},
  { type: "image", src: "https://i.postimg.cc/pTmPhhKP/185.jpg"},
  { type: "image", src: "https://i.postimg.cc/s2Djz0XQ/186.jpg"},
  { type: "image", src: "https://i.postimg.cc/63FtdWhn/187.jpg"},
  { type: "image", src: "https://i.postimg.cc/LsCH8BYy/188.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/gYWNL7ylEQc"},
  { type: "image", src: "https://i.postimg.cc/90TVb6xS/189.jpg"},
  { type: "image", src: "https://i.postimg.cc/vHFGTmTd/190.jpg"},
  { type: "image", src: "https://i.postimg.cc/kMtn7Snc/191.jpg"},
  { type: "image", src: "https://i.postimg.cc/0NTJNsJX/192.jpg"},
  { type: "image", src: "https://i.postimg.cc/jSy7jhfQ/IMG-20220715-222112.png"},
  { type: "image", src: "https://i.postimg.cc/gjwwbydh/193.jpg"},
  { type: "image", src: "https://i.postimg.cc/wv4tr4KH/194.jpg"},
  { type: "image", src: "https://i.postimg.cc/jjdPk7WH/IMG-20220716-001538.jpg"},
  { type: "image", src: "https://i.postimg.cc/xTvmfRMG/IMG-20220716-023845.jpg"},
  { type: "image", src: "https://i.postimg.cc/439sG8hs/195.jpg"},
  { type: "image", src: "https://i.postimg.cc/26NmS44v/IMG-20220716-005613.jpg"},
  { type: "image", src: "https://i.postimg.cc/xjRY9NqJ/196.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/F3ThsZMXjks"},
  { type: "youtube", src: "https://www.youtube.com/embed/LX3poWwnvTk"},
  { type: "image", src: "https://i.postimg.cc/mrCfJt0r/197.jpg"},
  { type: "image", src: "https://i.postimg.cc/nc5nWs3y/198.jpg"},
  { type: "image", src: "https://i.postimg.cc/dVrDmmJH/IMG-20220712-WA0001.png"},
  { type: "image", src: "https://i.postimg.cc/hvXtJVC0/199.jpg"},
  { type: "image", src: "https://i.postimg.cc/vBHBsJfk/200.jpg"},
  { type: "image", src: "https://i.postimg.cc/9M8fFLBM/201.jpg"},
  { type: "image", src: "https://i.postimg.cc/q7GRWJh2/202.jpg"},
  { type: "image", src: "https://i.postimg.cc/cCP4f62G/203.jpg"},
  { type: "image", src: "https://i.postimg.cc/NGn03PMC/204.jpg"},
  { type: "image", src: "https://i.postimg.cc/ZqJY8G7n/205.jpg"},
  { type: "image", src: "https://i.postimg.cc/y8mYS1T2/206.jpg"},
  { type: "image", src: "https://i.postimg.cc/RVn04QJS/207.jpg"},
  { type: "image", src: "https://i.postimg.cc/dVPV1kG8/208.jpg"},
  { type: "image", src: "https://i.postimg.cc/9f1mJLKp/209.jpg"},
  { type: "image", src: "https://i.postimg.cc/90wcXCM8/210.jpg"},
  { type: "image", src: "https://i.postimg.cc/FRR9qjQQ/211.jpg"},
  { type: "image", src: "https://i.postimg.cc/cHbsNrst/212.jpg"},
  { type: "image", src: "https://i.postimg.cc/HsCLW8wb/213.jpg"},
  { type: "image", src: "https://i.postimg.cc/0yk2DgHQ/214.jpg"},
  { type: "image", src: "https://i.postimg.cc/02dyz5nF/215.jpg"},
  { type: "youtube", src: "https://www.youtube.com/embed/CYPnpPyM3es"},
  { type: "youtube", src: "https://www.youtube.com/embed/_8SAkLzHJfM"},
];

let currentIndex = 1;
const totalMedia = media.length;

const mediaViewer = document.getElementById('mediaViewer');
const mediaInput = document.getElementById('mediaIndex');
const totalSpan = document.getElementById('totalMedia');
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');

totalSpan.textContent = totalMedia;

function loadMedia(index) {
  if (index < 1) index = totalMedia;
  if (index > totalMedia) index = 1;

  const item = media[index - 1];
  mediaViewer.innerHTML = "";

  if (item.type === "image") {
    const img = document.createElement("img");
    img.src = item.src;
    mediaViewer.appendChild(img);
  } else if (item.type === "youtube") {
    mediaViewer.innerHTML = "";
    mediaViewer.style.width = "432px";
    mediaViewer.style.height = "825px";

    const iframe = document.createElement("iframe");
    iframe.src = item.src + "?autoplay=1&rel=0";
    iframe.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture";
    iframe.allowFullscreen = false;
    iframe.style.width = "100%";  // ocupa todo el ancho del div
    iframe.style.height = "100%"; // ocupa todo el alto del div
    mediaViewer.appendChild(iframe);
  }

  currentIndex = index;
  mediaInput.value = index;
}

prevBtn.addEventListener('click', () => {
  loadMedia(currentIndex - 1);
});

nextBtn.addEventListener('click', () => {
  loadMedia(currentIndex + 1);
});

mediaInput.addEventListener('change', () => {
  loadMedia(parseInt(mediaInput.value));
});

loadMedia(currentIndex);