/*
{ type: "image", src: "" },
{ type: "youtube", src: "https://www.youtube.com/embed/" },
*/
const media =
[
    { type: "image", src: "https://i.postimg.cc/nLxgLKNV/1.jpg"},
    { type: "image", src: "https://i.postimg.cc/0Q24Yk8L/2.jpg"},
    { type: "image", src: "https://i.postimg.cc/HnFP1bQg/3.jpg"},
    { type: "image", src: "https://i.postimg.cc/KY5V3kyP/4.jpg"},
    { type: "image", src: "https://i.postimg.cc/bN2BHFhN/5.jpg"},
    { type: "image", src: "https://i.postimg.cc/7Z3tjGhF/6.jpg"},
    { type: "image", src: "https://i.postimg.cc/fbMqsz0J/7.jpg"},
    { type: "image", src: "https://i.postimg.cc/mgf6dNL3/8.jpg"},
    { type: "image", src: "https://i.postimg.cc/BvNYQrxN/9.jpg"},
    { type: "image", src: "https://i.postimg.cc/nzzds32x/10.jpg"},
    { type: "image", src: "https://i.postimg.cc/nzP3qqSD/11.jpg"},
    { type: "image", src: "https://i.postimg.cc/WzqX8txf/12.jpg"},
    { type: "image", src: "https://i.postimg.cc/rz6gPMky/13.jpg"},
    { type: "image", src: "https://i.postimg.cc/HsXCsLj2/14.jpg"},
    { type: "image", src: "https://i.postimg.cc/gcwWQsW1/15.jpg"},
    { type: "image", src: "https://i.postimg.cc/tRLjj6RJ/16.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/eyGhyAdtc30"},
    { type: "image", src: "https://i.postimg.cc/13S1gZqZ/17.jpg"},
    { type: "image", src: "https://i.postimg.cc/mr2xwNjX/18.jpg"},
    { type: "image", src: "https://i.postimg.cc/NjxqmP62/19.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/f0PHhWc2fb8"},
    { type: "image", src: "https://i.postimg.cc/W49BfFf2/20.jpg"},
    { type: "image", src: "https://i.postimg.cc/ydkMq1w0/21.jpg"},
    { type: "image", src: "https://i.postimg.cc/zB69qmr6/22.jpg"},
    { type: "image", src: "https://i.postimg.cc/4ycjd84d/23.jpg"},
    { type: "image", src: "https://i.postimg.cc/ZYvGVqPS/24.jpg"},
    { type: "image", src: "https://i.postimg.cc/QxpRZnnY/25.jpg"},
    { type: "image", src: "https://i.postimg.cc/jStBxQpx/26.jpg"},
    { type: "image", src: "https://i.postimg.cc/JzxvGH8b/27.jpg"},
    { type: "image", src: "https://i.postimg.cc/KYYVLccC/28.jpg"},
    { type: "image", src: "https://i.postimg.cc/0NH4Cgbj/29.jpg"},
    { type: "image", src: "https://i.postimg.cc/J0jdmGKH/30.jpg"},
    { type: "image", src: "https://i.postimg.cc/85J0Ky6H/31.jpg"},
    { type: "image", src: "https://i.postimg.cc/4dDFrzvT/32.jpg"},
    { type: "image", src: "https://i.postimg.cc/VLcVgWLq/33.jpg"},
    { type: "image", src: "https://i.postimg.cc/dQCfGxvQ/34.jpg"},
    { type: "image", src: "https://i.postimg.cc/sgj0dfW1/35.jpg"},
    { type: "image", src: "https://i.postimg.cc/TYqH45pZ/36.jpg"},
    { type: "image", src: "https://i.postimg.cc/cLFksq7h/37.jpg"},
    { type: "image", src: "https://i.postimg.cc/R0qshPXB/38.jpg"},
    { type: "image", src: "https://i.postimg.cc/4d9WbmD2/39.jpg"},
    { type: "image", src: "https://i.postimg.cc/TPSkDr4W/40.jpg"},
    { type: "image", src: "https://i.postimg.cc/90HJxcVm/41.jpg"},
    { type: "image", src: "https://i.postimg.cc/C5CJX9Lj/42.jpg"},
    { type: "image", src: "https://i.postimg.cc/c1fDvtMr/43.jpg"},
    { type: "image", src: "https://i.postimg.cc/RV9gKCXG/44.jpg"},
    { type: "image", src: "https://i.postimg.cc/hPrprFYn/45.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/sAN5jjplVKA"},
    { type: "image", src: "https://i.postimg.cc/fb3CDVRW/46.jpg"},
    { type: "image", src: "https://i.postimg.cc/P5VygWhF/47.jpg"},
    { type: "image", src: "https://i.postimg.cc/BnnN7YWK/48.jpg"},
    { type: "image", src: "https://i.postimg.cc/CKWN1wRG/49.jpg"},
    { type: "image", src: "https://i.postimg.cc/PxYMv0DB/50.jpg"},
    { type: "image", src: "https://i.postimg.cc/D0hPr5dm/51.jpg"},
    { type: "image", src: "https://i.postimg.cc/Kj5rJLJf/52.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/QHPy_Whx1Zs"},
    { type: "image", src: "https://i.postimg.cc/nVKkFbpm/53.jpg"},
    { type: "image", src: "https://i.postimg.cc/3JKZWSxc/54.jpg"},
    { type: "image", src: "https://i.postimg.cc/jdZ4fHWd/55.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/XAGT_qfNxlQ"},
    { type: "image", src: "https://i.postimg.cc/9Q0tYDTP/56.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/5LhDPCoeUFk"},
    { type: "image", src: "https://i.postimg.cc/3wDXzztd/57.jpg"},
    { type: "image", src: "https://i.postimg.cc/50dBJprp/58.jpg"},
    { type: "image", src: "https://i.postimg.cc/Y961CYK7/59.jpg"},
    { type: "image", src: "https://i.postimg.cc/C5wbB5Sq/60.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/l8x3XSBgZI8"},
    { type: "image", src: "https://i.postimg.cc/ry9161NC/61.jpg"},
    { type: "image", src: "https://i.postimg.cc/GtzGkRmS/62.jpg"},
    { type: "image", src: "https://i.postimg.cc/Ghhkb4M0/63.jpg"},
    { type: "image", src: "https://i.postimg.cc/BQY2bJyj/64.jpg"},
    { type: "image", src: "https://i.postimg.cc/HkrX7fDB/65.jpg"},
    { type: "image", src: "https://i.postimg.cc/zG4Ww0q5/66.jpg"},
    { type: "image", src: "https://i.postimg.cc/MGRB9VGB/67.jpg"},
    { type: "image", src: "https://i.postimg.cc/tJrnszBK/68.jpg"},
    { type: "image", src: "https://i.postimg.cc/fLN9py3r/69.jpg"},
    { type: "image", src: "https://i.postimg.cc/XJkCbWd7/70.jpg"},
    { type: "image", src: "https://i.postimg.cc/yx6S6Gyh/71.jpg"},
    { type: "image", src: "https://i.postimg.cc/gc4ZtYGg/72.jpg"},
    { type: "image", src: "https://i.postimg.cc/BQ61dd64/73.jpg"},
    { type: "image", src: "https://i.postimg.cc/y8ng2k36/243.png"},
    { type: "image", src: "https://i.postimg.cc/jj5wTtyH/244.png"},
    { type: "image", src: "https://i.postimg.cc/fTr0ZBtX/74.jpg"},
    { type: "image", src: "https://i.postimg.cc/zGHHfKKQ/75.jpg"},
    { type: "image", src: "https://i.postimg.cc/ZqkBvnL5/76.jpg"},
    { type: "image", src: "https://i.postimg.cc/pdD9fv0Y/77.jpg"},
    { type: "image", src: "https://i.postimg.cc/mDBPVnJx/78.jpg"},
    { type: "image", src: "https://i.postimg.cc/cCJrGndX/79.jpg"},
    { type: "image", src: "https://i.postimg.cc/hjsfYrRX/80.jpg"},
    { type: "image", src: "https://i.postimg.cc/VvH5fk61/81.jpg"},
    { type: "image", src: "https://i.postimg.cc/rFKKhxnp/82.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/7fAc5ZtVHeE"},
    { type: "image", src: "https://i.postimg.cc/8ky7Btb3/83.jpg"},
    { type: "image", src: "https://i.postimg.cc/Kvw4CjwD/84.jpg"},
    { type: "image", src: "https://i.postimg.cc/XY5XW30S/85.jpg"},
    { type: "image", src: "https://i.postimg.cc/wBdMTP6t/86.jpg"},
    { type: "image", src: "https://i.postimg.cc/k5F4Vc4T/87.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/6_TcDwA7jHg"},
    { type: "image", src: "https://i.postimg.cc/k4J5WbRq/88.jpg"},
    { type: "image", src: "https://i.postimg.cc/85Zz4zLW/89.jpg"},
    { type: "image", src: "https://i.postimg.cc/yxWYbCTG/90.jpg"},
    { type: "image", src: "https://i.postimg.cc/rsbF6Znw/91.jpg"},
    { type: "image", src: "https://i.postimg.cc/bJpJmP3c/238.png"},
    { type: "image", src: "https://i.postimg.cc/xTJ1GY8J/92.jpg"},
    { type: "image", src: "https://i.postimg.cc/8knCrspg/93.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/ZkT7xsCizCM"},
    { type: "image", src: "https://i.postimg.cc/FsMsDqkP/94.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/WVfR0prkuDM"},
    { type: "image", src: "https://i.postimg.cc/Mp1Z4Dyz/95.jpg"},
    { type: "image", src: "https://i.postimg.cc/LsR4M1TL/96.jpg"},
    { type: "image", src: "https://i.postimg.cc/g0Dzc2S5/97.jpg"},
    { type: "image", src: "https://i.postimg.cc/yd8VDC2N/98.jpg"},
    { type: "image", src: "https://i.postimg.cc/ydp79rzy/99.jpg"},
    { type: "image", src: "https://i.postimg.cc/2jTsbYWb/245.png"},
    { type: "image", src: "https://i.postimg.cc/2yqrxFkR/100.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/Zi8PifvkcR0"},
    { type: "image", src: "https://i.postimg.cc/4yrZ27yK/101.jpg"},
    { type: "image", src: "https://i.postimg.cc/J7g1zgx1/102.jpg"},
    { type: "image", src: "https://i.postimg.cc/bwfpQt4W/103.jpg"},
    { type: "image", src: "https://i.postimg.cc/Vk914N86/104.jpg"},
    { type: "image", src: "https://i.postimg.cc/TPRxsXdc/105.jpg"},
    { type: "image", src: "https://i.postimg.cc/zBvrJSRb/106.jpg"},
    { type: "image", src: "https://i.postimg.cc/JhP8VdtC/107.jpg"},
    { type: "image", src: "https://i.postimg.cc/fLPhktxH/108.jpg"},
    { type: "image", src: "https://i.postimg.cc/Bb1fFSpJ/109.jpg"},
    { type: "image", src: "https://i.postimg.cc/kD33F0YK/110.jpg"},
    { type: "image", src: "https://i.postimg.cc/bYKsBdKH/111.jpg"},
    { type: "image", src: "https://i.postimg.cc/ZKpCt4mk/112.jpg"},
    { type: "image", src: "https://i.postimg.cc/nhxMngVX/113.jpg"},
    { type: "image", src: "https://i.postimg.cc/3wJRvGv7/114.jpg"},
    { type: "image", src: "https://i.postimg.cc/d0H0m02C/115.jpg"},
    { type: "image", src: "https://i.postimg.cc/50X2PMgR/116.jpg"},
    { type: "image", src: "https://i.postimg.cc/yd2YtrrY/117.jpg"},
    { type: "image", src: "https://i.postimg.cc/zvWXrS9w/118.jpg"},
    { type: "image", src: "https://i.postimg.cc/8krCMNjF/119.jpg"},
    { type: "image", src: "https://i.postimg.cc/L6K8Vw1x/120.jpg"},
    { type: "image", src: "https://i.postimg.cc/Dyryp6Qn/121.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/mUBI75eCK9I"},
    { type: "image", src: "https://i.postimg.cc/nhTVpLwW/122.jpg"},
    { type: "image", src: "https://i.postimg.cc/43dfdTDx/123.jpg"},
    { type: "image", src: "https://i.postimg.cc/qR6psxMf/124.jpg"},
    { type: "image", src: "https://i.postimg.cc/KjXxJ3R1/125.jpg"},
    { type: "image", src: "https://i.postimg.cc/Zqcc7b46/246.png"},
    { type: "image", src: "https://i.postimg.cc/8C01f0GB/126.jpg"},
    { type: "image", src: "https://i.postimg.cc/1XpPTRqJ/127.jpg"},
    { type: "image", src: "https://i.postimg.cc/8PSTvv23/128.jpg"},
    { type: "image", src: "https://i.postimg.cc/pXJRJTxd/129.jpg"},
    { type: "image", src: "https://i.postimg.cc/RZC9sBVL/130.jpg"},
    { type: "image", src: "https://i.postimg.cc/GmMR654w/131.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/cQetzWY6HQo"},
    { type: "image", src: "https://i.postimg.cc/YSZHCLNd/132.jpg"},
    { type: "image", src: "https://i.postimg.cc/W3ZPFpXT/133.jpg"},
    { type: "image", src: "https://i.postimg.cc/qqdH8f5n/134.jpg"},
    { type: "image", src: "https://i.postimg.cc/MHb25sCL/135.jpg"},
    { type: "image", src: "https://i.postimg.cc/jdtr2bNY/136.jpg"},
    { type: "image", src: "https://i.postimg.cc/Vsj8z6JF/137.jpg"},
    { type: "image", src: "https://i.postimg.cc/YqRBmsfG/138.jpg"},
    { type: "image", src: "https://i.postimg.cc/cLJy7BXD/139.jpg"},
    { type: "image", src: "https://i.postimg.cc/q7tPSMfy/140.jpg"},
    { type: "image", src: "https://i.postimg.cc/ht3F2QYK/141.jpg"},
    { type: "image", src: "https://i.postimg.cc/zf9srZ5M/142.jpg"},
    { type: "image", src: "https://i.postimg.cc/DZLtfjwz/143.jpg"},
    { type: "image", src: "https://i.postimg.cc/QCDvFQFJ/144.jpg"},
    { type: "image", src: "https://i.postimg.cc/fyvpmVXn/145.jpg"},
    { type: "image", src: "https://i.postimg.cc/XNKTTzPH/146.jpg"},
    { type: "image", src: "https://i.postimg.cc/YqpJkxKp/147.jpg"},
    { type: "image", src: "https://i.postimg.cc/Cx5XnLxX/148.jpg"},
    { type: "image", src: "https://i.postimg.cc/ZKVXqy46/149.jpg"},
    { type: "image", src: "https://i.postimg.cc/mDWcKqyR/239.png"},
    { type: "image", src: "https://i.postimg.cc/tgxZSyP2/240.png"},
    { type: "image", src: "https://i.postimg.cc/W1tJZ04R/241.png"},
    { type: "image", src: "https://i.postimg.cc/VLKC5KmB/242.png"},
    { type: "image", src: "https://i.postimg.cc/Sx5YfjXn/247.png"},
    { type: "image", src: "https://i.postimg.cc/FHQHrcJg/248.png"},
    { type: "image", src: "https://i.postimg.cc/fRPFcn3L/150.jpg"},
    { type: "image", src: "https://i.postimg.cc/3wDq9SpZ/151.jpg"},
    { type: "image", src: "https://i.postimg.cc/rmXPH1N2/152.jpg"},
    { type: "image", src: "https://i.postimg.cc/Fzhnrh6P/153.jpg"},
    { type: "image", src: "https://i.postimg.cc/fLcrQV8t/154.jpg"},
    { type: "image", src: "https://i.postimg.cc/6qzbTDJB/155.jpg"},
    { type: "image", src: "https://i.postimg.cc/Kc5H9gKC/156.jpg"},
    { type: "image", src: "https://i.postimg.cc/DyyYRyL0/157.jpg"},
    { type: "image", src: "https://i.postimg.cc/WbWfVLwn/158.jpg"},
    { type: "image", src: "https://i.postimg.cc/52XKN7PM/159.jpg"},
    { type: "image", src: "https://i.postimg.cc/SxHTX65Y/160.jpg"},
    { type: "image", src: "https://i.postimg.cc/d0dWG7PH/161.jpg"},
    { type: "image", src: "https://i.postimg.cc/26D0GzCz/162.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/6f7_Xea6whE"},
    { type: "image", src: "https://i.postimg.cc/C1sm6WKb/163.jpg"},
    { type: "image", src: "https://i.postimg.cc/D0fBVBWH/164.jpg"},
    { type: "image", src: "https://i.postimg.cc/sxnK377X/165.jpg"},
    { type: "image", src: "https://i.postimg.cc/J7Kp3VvL/166.jpg"},
    { type: "image", src: "https://i.postimg.cc/sDXwwHCZ/167.jpg"},
    { type: "image", src: "https://i.postimg.cc/bNBLM0qV/168.jpg"},
    { type: "image", src: "https://i.postimg.cc/8ChHjqMx/169.jpg"},
    { type: "image", src: "https://i.postimg.cc/Z5vjh9Rb/170.jpg"},
    { type: "image", src: "https://i.postimg.cc/gJmKRNKj/171.jpg"},
    { type: "image", src: "https://i.postimg.cc/XJLkgd28/172.jpg"},
    { type: "image", src: "https://i.postimg.cc/15frpgDG/173.jpg"},
    { type: "image", src: "https://i.postimg.cc/3Nbjs7Q0/174.jpg"},
    { type: "image", src: "https://i.postimg.cc/2y5F9yMf/175.jpg"},
    { type: "image", src: "https://i.postimg.cc/sDq9KVJt/176.jpg"},
    { type: "image", src: "https://i.postimg.cc/YCFNsJnj/177.jpg"},
    { type: "image", src: "https://i.postimg.cc/N0w8qpSD/178.jpg"},
    { type: "image", src: "https://i.postimg.cc/s29YV5Rr/179.jpg"},
    { type: "image", src: "https://i.postimg.cc/wvqh336s/180.jpg"},
    { type: "image", src: "https://i.postimg.cc/GtNYMQvk/181.jpg"},
    { type: "image", src: "https://i.postimg.cc/RFgwt9Fp/182.jpg"},
    { type: "image", src: "https://i.postimg.cc/RhqKQ8JS/183.jpg"},
    { type: "image", src: "https://i.postimg.cc/HWPQspFV/184.jpg"},
    { type: "image", src: "https://i.postimg.cc/ZKGppwbm/185.jpg"},
    { type: "image", src: "https://i.postimg.cc/8zLWHLc6/186.jpg"},
    { type: "image", src: "https://i.postimg.cc/3w7GbW0b/187.jpg"},
    { type: "image", src: "https://i.postimg.cc/26SZrJwQ/188.jpg"},
    { type: "image", src: "https://i.postimg.cc/hjZ7jryH/189.jpg"},
    { type: "image", src: "https://i.postimg.cc/brGS2t4d/190.jpg"},
    { type: "image", src: "https://i.postimg.cc/C5WBCKV7/191.jpg"},
    { type: "image", src: "https://i.postimg.cc/kMZbPTtS/192.jpg"},
    { type: "image", src: "https://i.postimg.cc/BQK1S2xV/193.jpg"},
    { type: "image", src: "https://i.postimg.cc/sgCGv1mD/194.jpg"},
    { type: "image", src: "https://i.postimg.cc/zGwbW52w/195.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/89Hb667o4co"},
    { type: "youtube", src: "https://www.youtube.com/embed/SO4x9dAQGac"},
    { type: "image", src: "https://i.postimg.cc/LsHq37Gc/196.jpg"},
    { type: "image", src: "https://i.postimg.cc/Y90hJFr8/197.jpg"},
    { type: "image", src: "https://i.postimg.cc/3wnkS1Td/198.jpg"},
    { type: "image", src: "https://i.postimg.cc/XJPp3vXW/199.jpg"},
    { type: "image", src: "https://i.postimg.cc/LhK5Y0z0/200.jpg"},
    { type: "image", src: "https://i.postimg.cc/MZcYBM7y/201.jpg"},
    { type: "image", src: "https://i.postimg.cc/pVgJJWC3/202.jpg"},
    { type: "image", src: "https://i.postimg.cc/Qx1k62nC/203.jpg"},
    { type: "image", src: "https://i.postimg.cc/mg43Km0w/204.jpg"},
    { type: "image", src: "https://i.postimg.cc/t4zdbhbH/205.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/UAbj2_ydwho"},
    { type: "image", src: "https://i.postimg.cc/Y9f0GBv9/254.png"},
    { type: "image", src: "https://i.postimg.cc/8CPRzjkf/206.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/F9OktkDvM_Y"},
    { type: "image", src: "https://i.postimg.cc/Zq7rB407/207.jpg"},
    { type: "youtube", src: "https://www.youtube.com/embed/nvOjizMilOs"},
    { type: "youtube", src: "https://www.youtube.com/embed/vbtmKfQsMeI"},
    { type: "image", src: "https://i.postimg.cc/L5CsD69C/249.png"},
    { type: "image", src: "https://i.postimg.cc/PJrx18jv/250.png"},
    { type: "image", src: "https://i.postimg.cc/1RJ4sMGG/251.png"},
    { type: "image", src: "https://i.postimg.cc/QxCCt5mR/252.png"},
    { type: "youtube", src: "https://www.youtube.com/embed/qARFCRoSx60"},
    { type: "image", src: "https://i.postimg.cc/W3xg88G0/208.jpg"},
    { type: "image", src: "https://i.postimg.cc/50X88TCx/209.jpg"},
    { type: "image", src: "https://i.postimg.cc/QC55y7mw/210.jpg"},
    { type: "image", src: "https://i.postimg.cc/RCnchrmd/211.jpg"},
    { type: "image", src: "https://i.postimg.cc/28RnBH8D/212.jpg"},
    { type: "image", src: "https://i.postimg.cc/fRMX8J9q/213.jpg"},
    { type: "image", src: "https://i.postimg.cc/BQTH5xX1/214.jpg"},
    { type: "image", src: "https://i.postimg.cc/mrD9GJVQ/215.jpg"},
    { type: "image", src: "https://i.postimg.cc/N0zHGDPZ/216.jpg"},
    { type: "image", src: "https://i.postimg.cc/zGph68wz/217.jpg"},
];
  
  let currentIndex = 1;
  const totalMedia = media.length;
  
  const mediaViewer = document.getElementById('mediaViewer');
  const mediaInput = document.getElementById('mediaIndex');
  const totalSpan = document.getElementById('totalMedia');
  const prevBtn = document.getElementById('prevBtn');
  const nextBtn = document.getElementById('nextBtn');
  
  totalSpan.textContent = totalMedia;
  
  function loadMedia(index) {
    if (index < 1) index = totalMedia;
    if (index > totalMedia) index = 1;
  
    const item = media[index - 1];
    mediaViewer.innerHTML = "";
  
    if (item.type === "image") {
      const img = document.createElement("img");
      img.src = item.src;
      mediaViewer.appendChild(img);
    } else if (item.type === "youtube") {
      mediaViewer.innerHTML = "";
      mediaViewer.style.width = "432px";
      mediaViewer.style.height = "825px";
  
      const iframe = document.createElement("iframe");
      iframe.src = item.src + "?autoplay=1&rel=0";
      iframe.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture";
      iframe.allowFullscreen = false;
      iframe.style.width = "100%";  // ocupa todo el ancho del div
      iframe.style.height = "100%"; // ocupa todo el alto del div
      mediaViewer.appendChild(iframe);
    }
  
    currentIndex = index;
    mediaInput.value = index;
  }
  
  prevBtn.addEventListener('click', () => {
    loadMedia(currentIndex - 1);
  });
  
  nextBtn.addEventListener('click', () => {
    loadMedia(currentIndex + 1);
  });
  
  mediaInput.addEventListener('change', () => {
    loadMedia(parseInt(mediaInput.value));
  });
  
  loadMedia(currentIndex);